name: dotnet-clinician-org-sample

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/dotnet-clinician-org-sample.yml'
      - 'samples/dotnet/clinorg**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/dotnet-clinician-org-sample.yml'
      - 'samples/dotnet/clinorg**'

jobs:
  build:
    defaults:
      run:
        working-directory: samples/dotnet/clinorg
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore tools
      run: dotnet tool restore
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
