name: dotnet-clinician-org-sample

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/dotnet-clinician-org-sample.yml'
      - 'samples/dotnet/clinician-org-sample**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/dotnet-clinician-org-sample.yml'
      - 'samples/dotnet/clinician-org-sample**'

jobs:
  build:
    defaults:
      run:
        working-directory: samples/dotnet/clinician-org-sample
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
